//Test code generated by MISTA

package tvvs;

import tvvs.Coin;
import tvvs.VendingMachine;
import junit.framework.*;

public class VendingMachineTester_RAN extends TestCase{

	private VendingMachine vendingmachine;
	
	protected void setUp()  throws Exception {
		vendingmachine = new VendingMachine();
		vendingmachine.setDrink(COFFEE, 35, 1);
		vendingmachine.setDrink(JUICE, 110, 1);
		vendingmachine.setDrink(SODA, 105, 1);
	}
	
	public void test1() throws Exception {
		System.out.println("Test case 1");
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_1", vendingmachine.getDeposit()==100);
		assertTrue("1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("1_1_1", vendingmachine.getDeposit()==0);
		assertTrue("1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_1_1_1", vendingmachine.getDeposit()==25);
		assertTrue("1_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_1_1_1_1", vendingmachine.getDeposit()==35);
		assertTrue("1_1_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("1_1_1_1_1_1", vendingmachine.getDeposit()==0);
		assertTrue("1_1_1_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_1_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("", vendingmachine.getDeposit()==5);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("", vendingmachine.getDeposit()==10);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
	}

	public void test2() throws Exception {
		System.out.println("Test case 2");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_1_2", vendingmachine.getDeposit()==5);
		assertTrue("1_1_1_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_2", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_1_1_2_1", vendingmachine.getDeposit()==15);
		assertTrue("1_1_1_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_2_1", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("1_1_1_2_1_1", vendingmachine.getDeposit()==0);
		assertTrue("1_1_1_2_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_2_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_2_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("", vendingmachine.getDeposit()==25);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("", vendingmachine.getDeposit()==30);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
	}

	public void test3() throws Exception {
		System.out.println("Test case 3");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_1_1_2_2", vendingmachine.getDeposit()==30);
		assertTrue("1_1_1_2_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_2_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_2_2", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_1_1_2_2_1", vendingmachine.getDeposit()==40);
		assertTrue("1_1_1_2_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_2_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_2_2_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("", vendingmachine.getDeposit()==45);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
	}

	public void test4() throws Exception {
		System.out.println("Test case 4");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.purchase(COFFEE);
		assertTrue("1_1_2", vendingmachine.getDeposit()==0);
		assertTrue("1_1_2", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_2", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==100-35);
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_1_2_1", vendingmachine.getDeposit()==25);
		assertTrue("1_1_2_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_2_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_2_1_1", vendingmachine.getDeposit()==30);
		assertTrue("1_1_2_1_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_2_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_2_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_1_2_1_1_1", vendingmachine.getDeposit()==40);
		assertTrue("1_1_2_1_1_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_2_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_2_1_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 0));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("", vendingmachine.getDeposit()==5);
		assertTrue("", checkDrink(COFFEE, 35, 0));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 0));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
	}

	public void test5() throws Exception {
		System.out.println("Test case 5");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_1_3", vendingmachine.getDeposit()==110);
		assertTrue("1_1_3", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_3", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_3", checkDrink(SODA, 105, 1));
		vendingmachine.purchase(COFFEE);
		assertTrue("1_1_3_1", vendingmachine.getDeposit()==0);
		assertTrue("1_1_3_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_3_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_3_1", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==110-35);
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_1_3_1_1", vendingmachine.getDeposit()==25);
		assertTrue("1_1_3_1_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_3_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_3_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_3_1_1_1", vendingmachine.getDeposit()==30);
		assertTrue("1_1_3_1_1_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_3_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_3_1_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("", vendingmachine.getDeposit()==35);
		assertTrue("", checkDrink(COFFEE, 35, 0));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 0));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
	}

	public void test6() throws Exception {
		System.out.println("Test case 6");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_4", vendingmachine.getDeposit()==105);
		assertTrue("1_1_4", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_4", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_4", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("1_1_4_1", vendingmachine.getDeposit()==0);
		assertTrue("1_1_4_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_4_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_4_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_4_1_1", vendingmachine.getDeposit()==5);
		assertTrue("1_1_4_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_4_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_4_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_1_4_1_1_1", vendingmachine.getDeposit()==30);
		assertTrue("1_1_4_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_4_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_4_1_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("", vendingmachine.getDeposit()==40);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.purchase(COFFEE);
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 0));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==40-35);
	}

	public void test7() throws Exception {
		System.out.println("Test case 7");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.purchase(SODA);
		assertTrue("1_1_4_2", vendingmachine.getDeposit()==0);
		assertTrue("1_1_4_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_4_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_4_2", checkDrink(SODA, 105, 0));
		assertTrue("", vendingmachine.getChange()==105-105);
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_1_4_2_1", vendingmachine.getDeposit()==25);
		assertTrue("1_1_4_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_4_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_4_2_1", checkDrink(SODA, 105, 0));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_4_2_1_1", vendingmachine.getDeposit()==30);
		assertTrue("1_1_4_2_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_4_2_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_4_2_1_1", checkDrink(SODA, 105, 0));
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("", vendingmachine.getDeposit()==40);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 0));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 0));
	}

	public void test8() throws Exception {
		System.out.println("Test case 8");
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_2", vendingmachine.getDeposit()==10);
		assertTrue("1_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_2", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_1", vendingmachine.getDeposit()==15);
		assertTrue("1_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_2_1_1", vendingmachine.getDeposit()==115);
		assertTrue("1_2_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("1_2_1_1_1", vendingmachine.getDeposit()==0);
		assertTrue("1_2_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_2_1_1_1_1", vendingmachine.getDeposit()==25);
		assertTrue("1_2_1_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_1_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("", vendingmachine.getDeposit()==5);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
	}

	public void test9() throws Exception {
		System.out.println("Test case 9");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("", vendingmachine.getDeposit()==30);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
	}

	public void test10() throws Exception {
		System.out.println("Test case 10");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.purchase(JUICE);
		assertTrue("1_2_1_1_2", vendingmachine.getDeposit()==0);
		assertTrue("1_2_1_1_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_1_2", checkDrink(JUICE, 110, 0));
		assertTrue("1_2_1_1_2", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==115-110);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_1_1_2_1", vendingmachine.getDeposit()==5);
		assertTrue("1_2_1_1_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_1_2_1", checkDrink(JUICE, 110, 0));
		assertTrue("1_2_1_1_2_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("", vendingmachine.getDeposit()==30);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 0));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 0));
		assertTrue("", checkDrink(SODA, 105, 1));
	}

	public void test11() throws Exception {
		System.out.println("Test case 11");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_2_1_1_3", vendingmachine.getDeposit()==140);
		assertTrue("1_2_1_1_3", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_1_3", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_1_3", checkDrink(SODA, 105, 1));
		vendingmachine.purchase(COFFEE);
		assertTrue("1_2_1_1_3_1", vendingmachine.getDeposit()==0);
		assertTrue("1_2_1_1_3_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_2_1_1_3_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_1_3_1", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==140-35);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("", vendingmachine.getDeposit()==5);
		assertTrue("", checkDrink(COFFEE, 35, 0));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 0));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
	}

	public void test12() throws Exception {
		System.out.println("Test case 12");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_1_1_4", vendingmachine.getDeposit()==120);
		assertTrue("1_2_1_1_4", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_1_4", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_1_4", checkDrink(SODA, 105, 1));
		vendingmachine.purchase(COFFEE);
		assertTrue("1_2_1_1_4_1", vendingmachine.getDeposit()==0);
		assertTrue("1_2_1_1_4_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_2_1_1_4_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_1_4_1", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==120-35);
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("", vendingmachine.getDeposit()==25);
		assertTrue("", checkDrink(COFFEE, 35, 0));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 0));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
	}

	public void test13() throws Exception {
		System.out.println("Test case 13");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_2_2", vendingmachine.getDeposit()==35);
		assertTrue("1_2_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_2", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("1_2_2_1", vendingmachine.getDeposit()==0);
		assertTrue("1_2_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_2_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_2_1_1", vendingmachine.getDeposit()==5);
		assertTrue("1_2_2_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_2_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_2_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_2_1_1_1", vendingmachine.getDeposit()==10);
		assertTrue("1_2_2_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_2_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_2_1_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("", vendingmachine.getDeposit()==110);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.purchase(SODA);
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 0));
		assertTrue("", vendingmachine.getChange()==110-105);
	}

	public void test14() throws Exception {
		System.out.println("Test case 14");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_2_2", vendingmachine.getDeposit()==40);
		assertTrue("1_2_2_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_2_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_2_2", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("1_2_2_2_1", vendingmachine.getDeposit()==0);
		assertTrue("1_2_2_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_2_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_2_2_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_2_2_2_1_1", vendingmachine.getDeposit()==100);
		assertTrue("1_2_2_2_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_2_2_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_2_2_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.purchase(COFFEE);
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 0));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==100-35);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("", vendingmachine.getDeposit()==5);
		assertTrue("", checkDrink(COFFEE, 35, 0));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 0));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
	}

	public void test15() throws Exception {
		System.out.println("Test case 15");
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_3", vendingmachine.getDeposit()==5);
		assertTrue("1_3", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3", checkDrink(JUICE, 110, 1));
		assertTrue("1_3", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_3_1", vendingmachine.getDeposit()==15);
		assertTrue("1_3_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_3_1_1", vendingmachine.getDeposit()==20);
		assertTrue("1_3_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_3_1_1_1", vendingmachine.getDeposit()==120);
		assertTrue("1_3_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_1_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("1_3_1_1_1_1", vendingmachine.getDeposit()==0);
		assertTrue("1_3_1_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_1_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_1_1_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("", vendingmachine.getDeposit()==25);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
	}

	public void test16() throws Exception {
		System.out.println("Test case 16");
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.returnCoins();
		assertTrue("1_3_1_2", vendingmachine.getDeposit()==0);
		assertTrue("1_3_1_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_1_2", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_3_1_2_1", vendingmachine.getDeposit()==25);
		assertTrue("1_3_1_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_1_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_1_2_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_3_1_2_1_1", vendingmachine.getDeposit()==30);
		assertTrue("1_3_1_2_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_1_2_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_1_2_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("", vendingmachine.getDeposit()==130);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.purchase(SODA);
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 0));
		assertTrue("", vendingmachine.getChange()==130-105);
	}

	public void test17() throws Exception {
		System.out.println("Test case 17");
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_3_2", vendingmachine.getDeposit()==10);
		assertTrue("1_3_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_2", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("1_3_2_1", vendingmachine.getDeposit()==0);
		assertTrue("1_3_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_2_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_3_2_1_1", vendingmachine.getDeposit()==10);
		assertTrue("1_3_2_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_2_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_2_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_3_2_1_1_1", vendingmachine.getDeposit()==35);
		assertTrue("1_3_2_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_2_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_2_1_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("", vendingmachine.getDeposit()==135);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
	}

	public void test18() throws Exception {
		System.out.println("Test case 18");
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_3_2_2", vendingmachine.getDeposit()==20);
		assertTrue("1_3_2_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_2_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_2_2", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("1_3_2_2_1", vendingmachine.getDeposit()==0);
		assertTrue("1_3_2_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_2_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_2_2_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_3_2_2_1_1", vendingmachine.getDeposit()==100);
		assertTrue("1_3_2_2_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_2_2_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_2_2_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("", vendingmachine.getDeposit()==25);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 1));
	}

	public void test19() throws Exception {
		System.out.println("Test case 19");
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_4", vendingmachine.getDeposit()==25);
		assertTrue("1_4", checkDrink(COFFEE, 35, 1));
		assertTrue("1_4", checkDrink(JUICE, 110, 1));
		assertTrue("1_4", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_4_1", vendingmachine.getDeposit()==35);
		assertTrue("1_4_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_4_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_4_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_4_1_1", vendingmachine.getDeposit()==135);
		assertTrue("1_4_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_4_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_4_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.purchase(JUICE);
		assertTrue("1_4_1_1_1", vendingmachine.getDeposit()==0);
		assertTrue("1_4_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_4_1_1_1", checkDrink(JUICE, 110, 0));
		assertTrue("1_4_1_1_1", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==135-110);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_4_1_1_1_1", vendingmachine.getDeposit()==5);
		assertTrue("1_4_1_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_4_1_1_1_1", checkDrink(JUICE, 110, 0));
		assertTrue("1_4_1_1_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 0));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("", vendingmachine.getDeposit()==5);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 0));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 0));
		assertTrue("", checkDrink(SODA, 105, 1));
	}

	public void test20() throws Exception {
		System.out.println("Test case 20");
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_4_2", vendingmachine.getDeposit()==30);
		assertTrue("1_4_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_4_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_4_2", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_4_2_1", vendingmachine.getDeposit()==35);
		assertTrue("1_4_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_4_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_4_2_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_4_2_1_1", vendingmachine.getDeposit()==135);
		assertTrue("1_4_2_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_4_2_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_4_2_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.purchase(JUICE);
		assertTrue("1_4_2_1_1_1", vendingmachine.getDeposit()==0);
		assertTrue("1_4_2_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_4_2_1_1_1", checkDrink(JUICE, 110, 0));
		assertTrue("1_4_2_1_1_1", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==135-110);
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("", vendingmachine.getDeposit()==10);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 0));
		assertTrue("", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 1));
		assertTrue("", checkDrink(JUICE, 110, 0));
		assertTrue("", checkDrink(SODA, 105, 1));
	}


	  public static final String COFFEE = VendingMachine.COFFEE; 
	  public static final String JUICE = VendingMachine.JUICE; 
	  public static final String SODA = VendingMachine.SODA; 
		
	  private boolean checkDrink(String drink, int price, int count) {
	    if (drink.equalsIgnoreCase(COFFEE)) {
	      return vendingmachine.getCoffee().getPrice()==price && vendingmachine.getCoffee().getCount()==count;
	    }
	    
	    if (drink.equalsIgnoreCase(JUICE)) {
	      return vendingmachine.getJuice().getPrice()==price && vendingmachine.getJuice().getCount()==count;
	    }
	    
	    if (drink.equalsIgnoreCase(SODA)) {
	      return vendingmachine.getSoda().getPrice()==price && vendingmachine.getSoda().getCount()==count;
	    }
	    
	    return true;
	  }
	
	
	
}
